// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radargrpc.proto

package fsm.miaad.stubs;

public final class Radargrpc {
  private Radargrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 radarId = 1;</code>
     * @return The radarId.
     */
    long getRadarId();

    /**
     * <code>int64 vehicleId = 2;</code>
     * @return The vehicleId.
     */
    long getVehicleId();

    /**
     * <code>double speed = 3;</code>
     * @return The speed.
     */
    double getSpeed();

    /**
     * <code>double maxSpeed = 4;</code>
     * @return The maxSpeed.
     */
    double getMaxSpeed();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              radarId_ = input.readInt64();
              break;
            }
            case 16: {

              vehicleId_ = input.readInt64();
              break;
            }
            case 25: {

              speed_ = input.readDouble();
              break;
            }
            case 33: {

              maxSpeed_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fsm.miaad.stubs.Radargrpc.internal_static_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fsm.miaad.stubs.Radargrpc.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fsm.miaad.stubs.Radargrpc.Request.class, fsm.miaad.stubs.Radargrpc.Request.Builder.class);
    }

    public static final int RADARID_FIELD_NUMBER = 1;
    private long radarId_;
    /**
     * <code>int64 radarId = 1;</code>
     * @return The radarId.
     */
    public long getRadarId() {
      return radarId_;
    }

    public static final int VEHICLEID_FIELD_NUMBER = 2;
    private long vehicleId_;
    /**
     * <code>int64 vehicleId = 2;</code>
     * @return The vehicleId.
     */
    public long getVehicleId() {
      return vehicleId_;
    }

    public static final int SPEED_FIELD_NUMBER = 3;
    private double speed_;
    /**
     * <code>double speed = 3;</code>
     * @return The speed.
     */
    public double getSpeed() {
      return speed_;
    }

    public static final int MAXSPEED_FIELD_NUMBER = 4;
    private double maxSpeed_;
    /**
     * <code>double maxSpeed = 4;</code>
     * @return The maxSpeed.
     */
    public double getMaxSpeed() {
      return maxSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (radarId_ != 0L) {
        output.writeInt64(1, radarId_);
      }
      if (vehicleId_ != 0L) {
        output.writeInt64(2, vehicleId_);
      }
      if (speed_ != 0D) {
        output.writeDouble(3, speed_);
      }
      if (maxSpeed_ != 0D) {
        output.writeDouble(4, maxSpeed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (radarId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, radarId_);
      }
      if (vehicleId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, vehicleId_);
      }
      if (speed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, speed_);
      }
      if (maxSpeed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, maxSpeed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fsm.miaad.stubs.Radargrpc.Request)) {
        return super.equals(obj);
      }
      fsm.miaad.stubs.Radargrpc.Request other = (fsm.miaad.stubs.Radargrpc.Request) obj;

      if (getRadarId()
          != other.getRadarId()) return false;
      if (getVehicleId()
          != other.getVehicleId()) return false;
      if (java.lang.Double.doubleToLongBits(getSpeed())
          != java.lang.Double.doubleToLongBits(
              other.getSpeed())) return false;
      if (java.lang.Double.doubleToLongBits(getMaxSpeed())
          != java.lang.Double.doubleToLongBits(
              other.getMaxSpeed())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RADARID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRadarId());
      hash = (37 * hash) + VEHICLEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVehicleId());
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSpeed()));
      hash = (37 * hash) + MAXSPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxSpeed()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fsm.miaad.stubs.Radargrpc.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fsm.miaad.stubs.Radargrpc.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        fsm.miaad.stubs.Radargrpc.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fsm.miaad.stubs.Radargrpc.internal_static_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fsm.miaad.stubs.Radargrpc.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fsm.miaad.stubs.Radargrpc.Request.class, fsm.miaad.stubs.Radargrpc.Request.Builder.class);
      }

      // Construct using fsm.miaad.stubs.Radargrpc.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        radarId_ = 0L;

        vehicleId_ = 0L;

        speed_ = 0D;

        maxSpeed_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fsm.miaad.stubs.Radargrpc.internal_static_Request_descriptor;
      }

      @java.lang.Override
      public fsm.miaad.stubs.Radargrpc.Request getDefaultInstanceForType() {
        return fsm.miaad.stubs.Radargrpc.Request.getDefaultInstance();
      }

      @java.lang.Override
      public fsm.miaad.stubs.Radargrpc.Request build() {
        fsm.miaad.stubs.Radargrpc.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fsm.miaad.stubs.Radargrpc.Request buildPartial() {
        fsm.miaad.stubs.Radargrpc.Request result = new fsm.miaad.stubs.Radargrpc.Request(this);
        result.radarId_ = radarId_;
        result.vehicleId_ = vehicleId_;
        result.speed_ = speed_;
        result.maxSpeed_ = maxSpeed_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fsm.miaad.stubs.Radargrpc.Request) {
          return mergeFrom((fsm.miaad.stubs.Radargrpc.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fsm.miaad.stubs.Radargrpc.Request other) {
        if (other == fsm.miaad.stubs.Radargrpc.Request.getDefaultInstance()) return this;
        if (other.getRadarId() != 0L) {
          setRadarId(other.getRadarId());
        }
        if (other.getVehicleId() != 0L) {
          setVehicleId(other.getVehicleId());
        }
        if (other.getSpeed() != 0D) {
          setSpeed(other.getSpeed());
        }
        if (other.getMaxSpeed() != 0D) {
          setMaxSpeed(other.getMaxSpeed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fsm.miaad.stubs.Radargrpc.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fsm.miaad.stubs.Radargrpc.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long radarId_ ;
      /**
       * <code>int64 radarId = 1;</code>
       * @return The radarId.
       */
      public long getRadarId() {
        return radarId_;
      }
      /**
       * <code>int64 radarId = 1;</code>
       * @param value The radarId to set.
       * @return This builder for chaining.
       */
      public Builder setRadarId(long value) {
        
        radarId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 radarId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRadarId() {
        
        radarId_ = 0L;
        onChanged();
        return this;
      }

      private long vehicleId_ ;
      /**
       * <code>int64 vehicleId = 2;</code>
       * @return The vehicleId.
       */
      public long getVehicleId() {
        return vehicleId_;
      }
      /**
       * <code>int64 vehicleId = 2;</code>
       * @param value The vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleId(long value) {
        
        vehicleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 vehicleId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleId() {
        
        vehicleId_ = 0L;
        onChanged();
        return this;
      }

      private double speed_ ;
      /**
       * <code>double speed = 3;</code>
       * @return The speed.
       */
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>double speed = 3;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(double value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double speed = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        
        speed_ = 0D;
        onChanged();
        return this;
      }

      private double maxSpeed_ ;
      /**
       * <code>double maxSpeed = 4;</code>
       * @return The maxSpeed.
       */
      public double getMaxSpeed() {
        return maxSpeed_;
      }
      /**
       * <code>double maxSpeed = 4;</code>
       * @param value The maxSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setMaxSpeed(double value) {
        
        maxSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double maxSpeed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxSpeed() {
        
        maxSpeed_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final fsm.miaad.stubs.Radargrpc.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fsm.miaad.stubs.Radargrpc.Request();
    }

    public static fsm.miaad.stubs.Radargrpc.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fsm.miaad.stubs.Radargrpc.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string vehiclelicensePlate = 1;</code>
     * @return The vehiclelicensePlate.
     */
    java.lang.String getVehiclelicensePlate();
    /**
     * <code>string vehiclelicensePlate = 1;</code>
     * @return The bytes for vehiclelicensePlate.
     */
    com.google.protobuf.ByteString
        getVehiclelicensePlateBytes();

    /**
     * <code>string ownerfirstname = 2;</code>
     * @return The ownerfirstname.
     */
    java.lang.String getOwnerfirstname();
    /**
     * <code>string ownerfirstname = 2;</code>
     * @return The bytes for ownerfirstname.
     */
    com.google.protobuf.ByteString
        getOwnerfirstnameBytes();

    /**
     * <code>string ownerlastname = 3;</code>
     * @return The ownerlastname.
     */
    java.lang.String getOwnerlastname();
    /**
     * <code>string ownerlastname = 3;</code>
     * @return The bytes for ownerlastname.
     */
    com.google.protobuf.ByteString
        getOwnerlastnameBytes();

    /**
     * <code>double speed = 4;</code>
     * @return The speed.
     */
    double getSpeed();

    /**
     * <code>double maxSpeed = 6;</code>
     * @return The maxSpeed.
     */
    double getMaxSpeed();
  }
  /**
   * <pre>
   *infraction
   * </pre>
   *
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      vehiclelicensePlate_ = "";
      ownerfirstname_ = "";
      ownerlastname_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              vehiclelicensePlate_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ownerfirstname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ownerlastname_ = s;
              break;
            }
            case 33: {

              speed_ = input.readDouble();
              break;
            }
            case 49: {

              maxSpeed_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fsm.miaad.stubs.Radargrpc.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fsm.miaad.stubs.Radargrpc.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fsm.miaad.stubs.Radargrpc.Response.class, fsm.miaad.stubs.Radargrpc.Response.Builder.class);
    }

    public static final int VEHICLELICENSEPLATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object vehiclelicensePlate_;
    /**
     * <code>string vehiclelicensePlate = 1;</code>
     * @return The vehiclelicensePlate.
     */
    public java.lang.String getVehiclelicensePlate() {
      java.lang.Object ref = vehiclelicensePlate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehiclelicensePlate_ = s;
        return s;
      }
    }
    /**
     * <code>string vehiclelicensePlate = 1;</code>
     * @return The bytes for vehiclelicensePlate.
     */
    public com.google.protobuf.ByteString
        getVehiclelicensePlateBytes() {
      java.lang.Object ref = vehiclelicensePlate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehiclelicensePlate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNERFIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object ownerfirstname_;
    /**
     * <code>string ownerfirstname = 2;</code>
     * @return The ownerfirstname.
     */
    public java.lang.String getOwnerfirstname() {
      java.lang.Object ref = ownerfirstname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerfirstname_ = s;
        return s;
      }
    }
    /**
     * <code>string ownerfirstname = 2;</code>
     * @return The bytes for ownerfirstname.
     */
    public com.google.protobuf.ByteString
        getOwnerfirstnameBytes() {
      java.lang.Object ref = ownerfirstname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerfirstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNERLASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object ownerlastname_;
    /**
     * <code>string ownerlastname = 3;</code>
     * @return The ownerlastname.
     */
    public java.lang.String getOwnerlastname() {
      java.lang.Object ref = ownerlastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerlastname_ = s;
        return s;
      }
    }
    /**
     * <code>string ownerlastname = 3;</code>
     * @return The bytes for ownerlastname.
     */
    public com.google.protobuf.ByteString
        getOwnerlastnameBytes() {
      java.lang.Object ref = ownerlastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerlastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPEED_FIELD_NUMBER = 4;
    private double speed_;
    /**
     * <code>double speed = 4;</code>
     * @return The speed.
     */
    public double getSpeed() {
      return speed_;
    }

    public static final int MAXSPEED_FIELD_NUMBER = 6;
    private double maxSpeed_;
    /**
     * <code>double maxSpeed = 6;</code>
     * @return The maxSpeed.
     */
    public double getMaxSpeed() {
      return maxSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVehiclelicensePlateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vehiclelicensePlate_);
      }
      if (!getOwnerfirstnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ownerfirstname_);
      }
      if (!getOwnerlastnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ownerlastname_);
      }
      if (speed_ != 0D) {
        output.writeDouble(4, speed_);
      }
      if (maxSpeed_ != 0D) {
        output.writeDouble(6, maxSpeed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVehiclelicensePlateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vehiclelicensePlate_);
      }
      if (!getOwnerfirstnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ownerfirstname_);
      }
      if (!getOwnerlastnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ownerlastname_);
      }
      if (speed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, speed_);
      }
      if (maxSpeed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, maxSpeed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fsm.miaad.stubs.Radargrpc.Response)) {
        return super.equals(obj);
      }
      fsm.miaad.stubs.Radargrpc.Response other = (fsm.miaad.stubs.Radargrpc.Response) obj;

      if (!getVehiclelicensePlate()
          .equals(other.getVehiclelicensePlate())) return false;
      if (!getOwnerfirstname()
          .equals(other.getOwnerfirstname())) return false;
      if (!getOwnerlastname()
          .equals(other.getOwnerlastname())) return false;
      if (java.lang.Double.doubleToLongBits(getSpeed())
          != java.lang.Double.doubleToLongBits(
              other.getSpeed())) return false;
      if (java.lang.Double.doubleToLongBits(getMaxSpeed())
          != java.lang.Double.doubleToLongBits(
              other.getMaxSpeed())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VEHICLELICENSEPLATE_FIELD_NUMBER;
      hash = (53 * hash) + getVehiclelicensePlate().hashCode();
      hash = (37 * hash) + OWNERFIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerfirstname().hashCode();
      hash = (37 * hash) + OWNERLASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerlastname().hashCode();
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSpeed()));
      hash = (37 * hash) + MAXSPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxSpeed()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fsm.miaad.stubs.Radargrpc.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fsm.miaad.stubs.Radargrpc.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *infraction
     * </pre>
     *
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        fsm.miaad.stubs.Radargrpc.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fsm.miaad.stubs.Radargrpc.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fsm.miaad.stubs.Radargrpc.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fsm.miaad.stubs.Radargrpc.Response.class, fsm.miaad.stubs.Radargrpc.Response.Builder.class);
      }

      // Construct using fsm.miaad.stubs.Radargrpc.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vehiclelicensePlate_ = "";

        ownerfirstname_ = "";

        ownerlastname_ = "";

        speed_ = 0D;

        maxSpeed_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fsm.miaad.stubs.Radargrpc.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public fsm.miaad.stubs.Radargrpc.Response getDefaultInstanceForType() {
        return fsm.miaad.stubs.Radargrpc.Response.getDefaultInstance();
      }

      @java.lang.Override
      public fsm.miaad.stubs.Radargrpc.Response build() {
        fsm.miaad.stubs.Radargrpc.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fsm.miaad.stubs.Radargrpc.Response buildPartial() {
        fsm.miaad.stubs.Radargrpc.Response result = new fsm.miaad.stubs.Radargrpc.Response(this);
        result.vehiclelicensePlate_ = vehiclelicensePlate_;
        result.ownerfirstname_ = ownerfirstname_;
        result.ownerlastname_ = ownerlastname_;
        result.speed_ = speed_;
        result.maxSpeed_ = maxSpeed_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fsm.miaad.stubs.Radargrpc.Response) {
          return mergeFrom((fsm.miaad.stubs.Radargrpc.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fsm.miaad.stubs.Radargrpc.Response other) {
        if (other == fsm.miaad.stubs.Radargrpc.Response.getDefaultInstance()) return this;
        if (!other.getVehiclelicensePlate().isEmpty()) {
          vehiclelicensePlate_ = other.vehiclelicensePlate_;
          onChanged();
        }
        if (!other.getOwnerfirstname().isEmpty()) {
          ownerfirstname_ = other.ownerfirstname_;
          onChanged();
        }
        if (!other.getOwnerlastname().isEmpty()) {
          ownerlastname_ = other.ownerlastname_;
          onChanged();
        }
        if (other.getSpeed() != 0D) {
          setSpeed(other.getSpeed());
        }
        if (other.getMaxSpeed() != 0D) {
          setMaxSpeed(other.getMaxSpeed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fsm.miaad.stubs.Radargrpc.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fsm.miaad.stubs.Radargrpc.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object vehiclelicensePlate_ = "";
      /**
       * <code>string vehiclelicensePlate = 1;</code>
       * @return The vehiclelicensePlate.
       */
      public java.lang.String getVehiclelicensePlate() {
        java.lang.Object ref = vehiclelicensePlate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vehiclelicensePlate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vehiclelicensePlate = 1;</code>
       * @return The bytes for vehiclelicensePlate.
       */
      public com.google.protobuf.ByteString
          getVehiclelicensePlateBytes() {
        java.lang.Object ref = vehiclelicensePlate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vehiclelicensePlate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vehiclelicensePlate = 1;</code>
       * @param value The vehiclelicensePlate to set.
       * @return This builder for chaining.
       */
      public Builder setVehiclelicensePlate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vehiclelicensePlate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vehiclelicensePlate = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehiclelicensePlate() {
        
        vehiclelicensePlate_ = getDefaultInstance().getVehiclelicensePlate();
        onChanged();
        return this;
      }
      /**
       * <code>string vehiclelicensePlate = 1;</code>
       * @param value The bytes for vehiclelicensePlate to set.
       * @return This builder for chaining.
       */
      public Builder setVehiclelicensePlateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vehiclelicensePlate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ownerfirstname_ = "";
      /**
       * <code>string ownerfirstname = 2;</code>
       * @return The ownerfirstname.
       */
      public java.lang.String getOwnerfirstname() {
        java.lang.Object ref = ownerfirstname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ownerfirstname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ownerfirstname = 2;</code>
       * @return The bytes for ownerfirstname.
       */
      public com.google.protobuf.ByteString
          getOwnerfirstnameBytes() {
        java.lang.Object ref = ownerfirstname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ownerfirstname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ownerfirstname = 2;</code>
       * @param value The ownerfirstname to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerfirstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ownerfirstname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ownerfirstname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerfirstname() {
        
        ownerfirstname_ = getDefaultInstance().getOwnerfirstname();
        onChanged();
        return this;
      }
      /**
       * <code>string ownerfirstname = 2;</code>
       * @param value The bytes for ownerfirstname to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerfirstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ownerfirstname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ownerlastname_ = "";
      /**
       * <code>string ownerlastname = 3;</code>
       * @return The ownerlastname.
       */
      public java.lang.String getOwnerlastname() {
        java.lang.Object ref = ownerlastname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ownerlastname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ownerlastname = 3;</code>
       * @return The bytes for ownerlastname.
       */
      public com.google.protobuf.ByteString
          getOwnerlastnameBytes() {
        java.lang.Object ref = ownerlastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ownerlastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ownerlastname = 3;</code>
       * @param value The ownerlastname to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerlastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ownerlastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ownerlastname = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerlastname() {
        
        ownerlastname_ = getDefaultInstance().getOwnerlastname();
        onChanged();
        return this;
      }
      /**
       * <code>string ownerlastname = 3;</code>
       * @param value The bytes for ownerlastname to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerlastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ownerlastname_ = value;
        onChanged();
        return this;
      }

      private double speed_ ;
      /**
       * <code>double speed = 4;</code>
       * @return The speed.
       */
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>double speed = 4;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(double value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double speed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        
        speed_ = 0D;
        onChanged();
        return this;
      }

      private double maxSpeed_ ;
      /**
       * <code>double maxSpeed = 6;</code>
       * @return The maxSpeed.
       */
      public double getMaxSpeed() {
        return maxSpeed_;
      }
      /**
       * <code>double maxSpeed = 6;</code>
       * @param value The maxSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setMaxSpeed(double value) {
        
        maxSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double maxSpeed = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxSpeed() {
        
        maxSpeed_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final fsm.miaad.stubs.Radargrpc.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fsm.miaad.stubs.Radargrpc.Response();
    }

    public static fsm.miaad.stubs.Radargrpc.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fsm.miaad.stubs.Radargrpc.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017radargrpc.proto\"N\n\007Request\022\017\n\007radarId\030" +
      "\001 \001(\003\022\021\n\tvehicleId\030\002 \001(\003\022\r\n\005speed\030\003 \001(\001\022" +
      "\020\n\010maxSpeed\030\004 \001(\001\"w\n\010Response\022\033\n\023vehicle" +
      "licensePlate\030\001 \001(\t\022\026\n\016ownerfirstname\030\002 \001" +
      "(\t\022\025\n\rownerlastname\030\003 \001(\t\022\r\n\005speed\030\004 \001(\001" +
      "\022\020\n\010maxSpeed\030\006 \001(\0012>\n\017SpeedingService\022+\n" +
      "\020SpeedingRandomly\022\010.Request\032\t.Response(\001" +
      "0\001B\021\n\017fsm.miaad.stubsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "RadarId", "VehicleId", "Speed", "MaxSpeed", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "VehiclelicensePlate", "Ownerfirstname", "Ownerlastname", "Speed", "MaxSpeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
