spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:2001/
          predicates:
            - Path= /customers/**
        - id: r2
          uri: http://localhost:2002/
          predicates:
            - Path= /products/**

